apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app1
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app2
---
apiVersion: v1
kind: Service
metadata:
  name: app3-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app3